// Ülkelere göre şehirler ve havaalanı kodları
export const citiesByCountry = {
  Turkey: [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Antalya",
    "Bursa",
    "Adana",
    "Konya",
    "Gaziantep",
    "Mersin",
    "Kayseri",
    "Eskişehir",
    "Diyarbakır",
    "Şanlıurfa",
    "Denizli",
    "Samsun",
    "Malatya",
    "Trabzon",
    "Van",
    "Erzurum",
    "Elazığ",
    "Batman",
    "Mardin",
    "Hatay",
    "Muğla",
    "Aydın",
  ],
  "United Arab Emirates": [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain",
    "Al Ain",
    "Khor Fakkan",
    "Dibba",
    "Kalba",
    "Madinat Zayed",
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Taif",
    "Tabuk",
    "Buraidah",
    "Khamis Mushait",
    "Abha",
    "Najran",
    "Jazan",
    "Hail",
    "Yanbu",
    "Al Khobar",
    "Jubail",
    "Arar",
    "Sakaka",
    "Al Bahah",
    "Qassim",
    "Al Qatif",
    "Hafar Al-Batin",
    "AlUla",
    "Neom",
    "Al Ahsa",
    "Dhahran",
    "Thuwal",
    "King Abdullah Economic City",
    "Ras Tanura",
    "Qurayyat",
    "Turaif",
    "Rafha",
    "Al Wajh",
    "Umluj",
    "Farasan",
    "Sharurah",
    "Gurayat",
    "Dawadmi",
    "Afif",
    "Al Majmaah",
    "Shaqra",
    "Al Ghat",
    "Rumah",
    "Al Artawiyah",
    "Layla",
    "Al Kharj",
    "Al Aflaj",
    "Wadi al-Dawasir",
    "As Sulayyil",
    "Hotat Bani Tamim",
    "Al Hariq",
    "Al Muzahimiyah",
    "Diriyah",
    "Al Uyaynah",
    "Irqah",
    "Thadiq",
    "Huraymila",
    "Al Quway'iyah",
    "As Salam",
    "Marat",
    "Afif",
    "Al Bukayriyah",
    "Ar Rass",
    "Unayzah",
    "Riyadh Al Khabra",
    "Al Badai",
    "Uyun AlJiwa",
    "Al Asyah",
    "Al Bukairiyah",
    "Dhariyah",
    "Al Mithnab",
    "Al Shamli",
    "Hail",
    "Baqaa",
    "Al Ghazalah",
    "Ash Shinan",
    "As Sulaymi",
    "Jubbah",
    "Al Hajar",
    "Ash Shamli",
  ],
  Egypt: [
    "Cairo",
    "Alexandria",
    "Giza",
    "Sharm El Sheikh",
    "Luxor",
    "Aswan",
    "Hurghada",
    "Port Said",
    "Suez",
    "Ismailia",
    "Tanta",
    "Mansoura",
    "Asyut",
    "Zagazig",
    "Damietta",
    "Faiyum",
    "Minya",
    "Sohag",
    "Qena",
    "Beni Suef",
    "Kafr El Sheikh",
    "Marsa Alam",
    "Dahab",
    "El Gouna",
  ],
  "United States": [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "San Francisco",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington DC",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Long Beach",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Virginia Beach",
    "Omaha",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "Tampa",
    "New Orleans",
  ],
  "United Kingdom": [
    "London",
    "Birmingham",
    "Manchester",
    "Glasgow",
    "Liverpool",
    "Bristol",
    "Edinburgh",
    "Leeds",
    "Sheffield",
    "Newcastle",
    "Belfast",
    "Leicester",
    "Coventry",
    "Nottingham",
    "Cardiff",
    "Bradford",
    "Stoke-on-Trent",
    "Wolverhampton",
    "Plymouth",
    "Derby",
    "Southampton",
    "Swansea",
    "Salford",
    "Aberdeen",
    "Westminster",
    "Portsmouth",
    "York",
    "Peterborough",
    "Dundee",
    "Lancaster",
    "Oxford",
    "Newport",
    "Preston",
    "St Albans",
    "Norwich",
    "Chester",
    "Cambridge",
    "Salisbury",
    "Exeter",
    "Gloucester",
    "Lisburn",
    "Chichester",
    "Winchester",
    "Lichfield",
    "Hereford",
    "Salisbury",
    "Truro",
    "Ely",
    "Bangor",
    "St Davids",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Saint-Etienne",
    "Toulon",
    "Le Havre",
    "Grenoble",
    "Dijon",
    "Angers",
    "Villeurbanne",
    "Le Mans",
    "Aix-en-Provence",
    "Clermont-Ferrand",
    "Brest",
    "Tours",
    "Limoges",
    "Amiens",
    "Annecy",
    "Perpignan",
    "Boulogne-Billancourt",
    "Metz",
    "Besançon",
    "Orléans",
    "Mulhouse",
    "Rouen",
    "Caen",
    "Nancy",
    "Saint-Denis",
    "Argenteuil",
    "Montreuil",
    "Roubaix",
    "Tourcoing",
    "Nanterre",
    "Avignon",
    "Créteil",
    "Dunkerque",
    "Poitiers",
    "Asnières-sur-Seine",
    "Courbevoie",
    "Versailles",
    "Colombes",
  ],
  Germany: [
    "Berlin",
    "Hamburg",
    "Munich",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Bremen",
    "Dresden",
    "Hanover",
    "Nuremberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle",
    "Magdeburg",
    "Freiburg",
    "Krefeld",
    "Lübeck",
    "Oberhausen",
    "Erfurt",
    "Mainz",
    "Rostock",
    "Kassel",
    "Hagen",
    "Potsdam",
    "Saarbrücken",
    "Hamm",
    "Mülheim",
    "Ludwigshafen",
    "Leverkusen",
    "Oldenburg",
    "Neuss",
    "Heidelberg",
  ],
  Italy: [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Bari",
    "Catania",
    "Venice",
    "Verona",
    "Messina",
    "Padua",
    "Trieste",
    "Taranto",
    "Brescia",
    "Prato",
    "Parma",
    "Modena",
    "Reggio Calabria",
    "Reggio Emilia",
    "Perugia",
    "Livorno",
    "Ravenna",
    "Cagliari",
    "Foggia",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Sassari",
    "Latina",
    "Giugliano",
    "Monza",
    "Syracuse",
    "Pescara",
    "Bergamo",
    "Forlì",
    "Trento",
    "Vicenza",
    "Terni",
    "Bolzano",
    "Novara",
    "Piacenza",
    "Ancona",
    "Andria",
    "Arezzo",
    "Udine",
    "Cesena",
    "Lecce",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "L'Hospitalet",
    "A Coruña",
    "Vitoria-Gasteiz",
    "Granada",
    "Elche",
    "Oviedo",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez",
    "Sabadell",
    "Móstoles",
    "Santa Cruz",
    "Pamplona",
    "Almería",
    "Alcalá de Henares",
    "Fuenlabrada",
    "Leganés",
    "Donostia",
    "Burgos",
    "Santander",
    "Castellón",
    "Getafe",
    "Alcorcón",
    "Logroño",
    "Badajoz",
    "Salamanca",
    "Huelva",
    "Marbella",
    "Lleida",
    "Tarragona",
    "León",
    "Cadiz",
    "Dos Hermanas",
    "Torrejón",
  ],
  Japan: [
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Kyoto",
    "Fukuoka",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Kitakyushu",
    "Chiba",
    "Sakai",
    "Niigata",
    "Hamamatsu",
    "Okayama",
    "Sagamihara",
    "Shizuoka",
    "Kumamoto",
    "Kagoshima",
    "Matsuyama",
    "Kanazawa",
    "Utsunomiya",
    "Matsudo",
    "Kawaguchi",
    "Ichikawa",
    "Fujisawa",
    "Hachioji",
    "Nara",
    "Machida",
    "Kasukabe",
    "Iwaki",
    "Naha",
    "Takatsuki",
    "Oita",
    "Toyota",
    "Wakayama",
    "Kochi",
    "Miyazaki",
    "Nara",
    "Suita",
    "Hirakata",
    "Tokorozawa",
    "Nagano",
    "Koshigaya",
    "Kawagoe",
    "Maebashi",
    "Akita",
  ],
  China: [
    "Shanghai",
    "Beijing",
    "Guangzhou",
    "Shenzhen",
    "Tianjin",
    "Wuhan",
    "Chongqing",
    "Chengdu",
    "Nanjing",
    "Xi'an",
    "Hangzhou",
    "Shenyang",
    "Harbin",
    "Jinan",
    "Qingdao",
    "Dalian",
    "Zhengzhou",
    "Shantou",
    "Jinan",
    "Changchun",
    "Kunming",
    "Changsha",
    "Taiyuan",
    "Xiamen",
    "Hefei",
    "Shijiazhuang",
    "Urumqi",
    "Fuzhou",
    "Wuxi",
    "Zhongshan",
    "Wenzhou",
    "Nanning",
    "Nanchang",
    "Guiyang",
    "Lanzhou",
    "Zibo",
    "Changzhou",
    "Xuzhou",
    "Tangshan",
    "Baotou",
    "Handan",
    "Weihai",
    "Fushun",
    "Yantai",
    "Zhuhai",
    "Haikou",
    "Luoyang",
    "Yinchuan",
    "Liuzhou",
    "Anshan",
    "Huizhou",
  ],
  India: [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Pune",
    "Surat",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Kalyan-Dombivali",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Allahabad",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Guwahati",
    "Chandigarh",
    "Solapur",
    "Hubli-Dharwad",
  ],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Belém",
    "Goiânia",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "São Gonçalo",
    "Maceió",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Teresina",
    "Natal",
    "Campo Grande",
    "São Bernardo do Campo",
    "João Pessoa",
    "Santo André",
    "Osasco",
    "Jaboatão dos Guararapes",
    "São José dos Campos",
    "Ribeirão Preto",
    "Uberlândia",
    "Contagem",
    "Sorocaba",
    "Aracaju",
    "Feira de Santana",
    "Cuiabá",
    "Joinville",
    "Aparecida de Goiânia",
    "Londrina",
    "Juiz de Fora",
    "Ananindeua",
    "Porto Velho",
    "Serra",
    "Niterói",
    "Caxias do Sul",
    "Campos dos Goytacazes",
    "Vila Velha",
    "Florianópolis",
    "Mauá",
    "Carapicuíba",
    "Olinda",
  ],
  Australia: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Newcastle",
    "Canberra",
    "Wollongong",
    "Hobart",
    "Geelong",
    "Townsville",
    "Cairns",
    "Darwin",
    "Toowoomba",
    "Ballarat",
    "Bendigo",
    "Albury",
    "Launceston",
    "Mackay",
    "Rockhampton",
    "Bunbury",
    "Bundaberg",
    "Coffs Harbour",
    "Wagga Wagga",
    "Hervey Bay",
    "Mildura",
    "Shepparton",
    "Port Macquarie",
    "Gladstone",
    "Tamworth",
    "Traralgon",
    "Orange",
    "Dubbo",
    "Geraldton",
    "Bowral",
    "Bathurst",
    "Nowra",
    "Warrnambool",
    "Kalgoorlie",
    "Devonport",
    "Burnie",
    "Alice Springs",
    "Whyalla",
    "Mount Gambier",
    "Lismore",
    "Nelson Bay",
    "Broken Hill",
    "Emerald",
    "Broome",
  ],
  Afghanistan: [
    "Kabul",
    "Kandahar",
    "Herat",
    "Mazar-i-Sharif",
    "Jalalabad",
    "Kunduz",
    "Ghazni",
    "Balkh",
    "Bamyan",
    "Farah",
    "Lashkar Gah",
    "Taloqan",
    "Khost",
    "Gardez",
    "Zaranj",
    "Pul-e-Khumri",
    "Charikar",
    "Sheberghan",
    "Asadabad",
    "Baghlan",
  ],
  Albania: [
    "Tirana",
    "Durrës",
    "Vlorë",
    "Elbasan",
    "Shkodër",
    "Korçë",
    "Fier",
    "Berat",
    "Lushnjë",
    "Kavajë",
    "Gjirokastër",
    "Sarandë",
    "Laç",
    "Kukës",
    "Lezhë",
    "Pogradec",
    "Peshkopi",
    "Kuçovë",
    "Krujë",
    "Burrel",
  ],
  Armenia: [
    "Yerevan",
    "Gyumri",
    "Vanadzor",
    "Vagharshapat",
    "Hrazdan",
    "Abovyan",
    "Kapan",
    "Goris",
    "Ashtarak",
    "Artashat",
    "Sevan",
    "Charentsavan",
    "Armavir",
    "Ararat",
    "Ijevan",
    "Sisian",
    "Gavar",
    "Dilijan",
    "Masis",
    "Alaverdi",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "San Miguel de Tucumán",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Santiago del Estero",
    "Corrientes",
    "Posadas",
    "Neuquén",
    "Bahía Blanca",
    "Paraná",
    "Formosa",
    "San Luis",
    "La Rioja",
    "Catamarca",
    "Río Cuarto",
    "Comodoro Rivadavia",
    "Concordia",
    "San Rafael",
    "Tandil",
    "Venado Tuerto",
    "Santa Rosa",
    "Río Gallegos",
    "Ushuaia",
  ],
  Austria: [
    "Vienna",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Villach",
    "Wels",
    "Sankt Pölten",
    "Dornbirn",
    "Steyr",
    "Wiener Neustadt",
    "Feldkirch",
    "Bregenz",
    "Leonding",
    "Klosterneuburg",
    "Baden",
    "Wolfsberg",
    "Leoben",
    "Krems",
    "Traun",
    "Amstetten",
    "Kapfenberg",
    "Mödling",
    "Hallein",
  ],
  Azerbaijan: [
    "Baku",
    "Ganja",
    "Sumqayit",
    "Mingachevir",
    "Qabalá",
    "Lankaran",
    "Nakhchivan",
    "Sheki",
    "Yevlax",
    "Shirvan",
    "Quba",
    "Shamakhi",
    "Goychay",
    "Barda",
    "Tartar",
    "Bilasuvar",
    "Saatly",
    "Sabirabad",
    "Salyan",
    "Masally",
  ],
  "Bosnia and Herzegovina": [
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Bijeljina",
    "Brčko",
    "Prijedor",
    "Trebinje",
    "Doboj",
    "Cazin",
    "Bugojno",
    "Goražde",
    "Visoko",
    "Konjic",
    "Gračanica",
    "Gradačac",
    "Bosanska Krupa",
    "Mrkonjić Grad",
    "Foča",
  ],
  Bangladesh: [
    "Dhaka",
    "Chittagong",
    "Sylhet",
    "Rajshahi",
    "Khulna",
    "Barisal",
    "Rangpur",
    "Comilla",
    "Mymensingh",
    "Gazipur",
    "Narayanganj",
    "Savar",
    "Cox's Bazar",
    "Jessore",
    "Bogra",
    "Dinajpur",
    "Pabna",
    "Kushtia",
    "Faridpur",
    "Tangail",
  ],
  Belgium: [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Liège",
    "Bruges",
    "Namur",
    "Leuven",
    "Mons",
    "Aalst",
    "Mechelen",
    "La Louvière",
    "Kortrijk",
    "Hasselt",
    "Sint-Niklaas",
    "Ostend",
    "Tournai",
    "Genk",
    "Seraing",
    "Roeselare",
    "Mouscron",
    "Verviers",
    "Dendermonde",
    "Beringen",
    "Turnhout",
  ],
  Bulgaria: [
    "Sofia",
    "Plovdiv",
    "Varna",
    "Burgas",
    "Ruse",
    "Stara Zagora",
    "Pleven",
    "Sliven",
    "Dobrich",
    "Shumen",
    "Pernik",
    "Haskovo",
    "Yambol",
    "Pazardzhik",
    "Blagoevgrad",
    "Veliko Tarnovo",
    "Vratsa",
    "Gabrovo",
    "Asenovgrad",
    "Vidin",
    "Kazanlak",
    "Kyustendil",
    "Kardzhali",
    "Montana",
    "Dimitrovgrad",
  ],
  Bahrain: [
    "Manama",
    "Riffa",
    "Muharraq",
    "Hamad Town",
    "A'ali",
    "Isa Town",
    "Sitra",
    "Budaiya",
    "Jidhafs",
    "Al-Malikiyah",
    "Sanabis",
    "Tubli",
    "Barbar",
    "Galali",
    "Hidd",
    "Karbabad",
    "Sanad",
    "Dar Kulaib",
    "Dumistan",
    "Jaw",
  ],
  Bolivia: [
    "La Paz",
    "Santa Cruz",
    "Cochabamba",
    "Sucre",
    "Oruro",
    "Tarija",
    "Potosí",
    "Trinidad",
    "Cobija",
    "Riberalta",
    "Montero",
    "Quillacollo",
    "Sacaba",
    "Warnes",
    "Yacuiba",
    "Camiri",
    "Guayaramerín",
    "Villazón",
    "Vinto",
    "Tiquipaya",
  ],
  Canada: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
    "Saskatoon",
    "St. Catharines",
    "Regina",
    "Sherbrooke",
    "Kelowna",
    "Barrie",
    "Abbotsford",
    "Sudbury",
    "Kingston",
    "Saguenay",
    "Trois-Rivières",
    "Guelph",
    "Cambridge",
    "Whitby",
    "Coquitlam",
    "Saanich",
    "Burlington",
    "Richmond",
    "Oakville",
    "Burnaby",
    "Red Deer",
    "Brantford",
    "Lethbridge",
    "North Vancouver",
    "Kamloops",
  ],
  Switzerland: [
    "Zurich",
    "Geneva",
    "Basel",
    "Bern",
    "Lausanne",
    "Winterthur",
    "Lucerne",
    "St. Gallen",
    "Lugano",
    "Biel/Bienne",
    "Thun",
    "Köniz",
    "La Chaux-de-Fonds",
    "Schaffhausen",
    "Fribourg",
    "Chur",
    "Vernier",
    "Neuchâtel",
    "Uster",
    "Sion",
    "Emmen",
    "Zug",
    "Yverdon-les-Bains",
    "Dübendorf",
    "Dietikon",
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Rancagua",
    "Talca",
    "Arica",
    "Chillán",
    "Iquique",
    "Los Ángeles",
    "Puerto Montt",
    "Calama",
    "Coquimbo",
    "Osorno",
    "Valdivia",
    "Punta Arenas",
    "Quilpué",
    "Villa Alemana",
    "Curicó",
    "Melipilla",
    "Copiapó",
    "San Antonio",
    "Linares",
  ],
  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Santa Marta",
    "Ibagué",
    "Pasto",
    "Manizales",
    "Neiva",
    "Soledad",
    "Armenia",
    "Villavicencio",
    "Soacha",
    "Valledupar",
    "Montería",
    "Itagüí",
    "Palmira",
    "Buenaventura",
    "Floridablanca",
    "Sincelejo",
    "Popayán",
    "Dosquebradas",
    "Envigado",
    "Tuluá",
    "Cartago",
    "Bello",
  ],
  "Costa Rica": [
    "San José",
    "Cartago",
    "Puntarenas",
    "Limón",
    "Alajuela",
    "Heredia",
    "Guanacaste",
    "Liberia",
    "Puntarenas",
    "Jacó",
    "Manuel Antonio",
    "Tamarindo",
    "Monteverde",
    "La Fortuna",
    "Dominical",
    "Uvita",
    "Nosara",
    "Samara",
    "Cahuita",
    "Puerto Viejo",
  ],
  Cyprus: [
    "Nicosia",
    "Limassol",
    "Larnaca",
    "Paphos",
    "Famagusta",
    "Kyrenia",
    "Protaras",
    "Ayia Napa",
    "Paralimni",
    "Morphou",
    "Polis",
    "Lefkara",
    "Platres",
    "Omodos",
    "Kakopetria",
    "Pedoulas",
    "Troodos",
    "Kato Paphos",
    "Coral Bay",
    "Pissouri",
  ],
  "Czech Republic": [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzen",
    "Liberec",
    "Olomouc",
    "České Budějovice",
    "Hradec Králové",
    "Ústí nad Labem",
    "Pardubice",
    "Zlín",
    "Havířov",
    "Kladno",
    "Most",
    "Opava",
    "Frýdek-Místek",
    "Karviná",
    "Jihlava",
    "Teplice",
    "Děčín",
    "Karlovy Vary",
    "Jablonec nad Nisou",
    "Mladá Boleslav",
    "Prostějov",
    "Přerov",
  ],
  Denmark: [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Herning",
    "Helsingør",
    "Silkeborg",
    "Næstved",
    "Fredericia",
    "Viborg",
    "Køge",
    "Holstebro",
    "Taastrup",
    "Slagelse",
    "Hillerød",
    "Sønderborg",
    "Svendborg",
    "Hjørring",
    "Frederikshavn",
  ],
  "Dominican Republic": [
    "Santo Domingo",
    "Santiago",
    "La Romana",
    "San Pedro de Macorís",
    "La Vega",
    "Puerto Plata",
    "Baní",
    "Bonao",
    "San Francisco de Macorís",
    "Higüey",
    "Moca",
    "San Juan",
    "Barahona",
    "Azua",
    "Mao",
    "San Cristóbal",
    "Cotuí",
    "Nagua",
    "Monte Cristi",
    "Jarabacoa",
  ],
  Algeria: [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Djelfa",
    "Sétif",
    "Sidi Bel Abbès",
    "Biskra",
    "Tébessa",
    "El Oued",
    "Skikda",
    "Tiaret",
    "Béjaïa",
    "Tlemcen",
    "Ouargla",
    "Mostaganem",
    "Bordj Bou Arréridj",
    "Chlef",
    "Médéa",
    "Tizi Ouzou",
    "Béchar",
    "Boumerdès",
    "El Eulma",
  ],
  Ecuador: [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Santo Domingo",
    "Machala",
    "Manta",
    "Portoviejo",
    "Ambato",
    "Riobamba",
    "Loja",
    "Esmeraldas",
    "Ibarra",
    "Milagro",
    "Quevedo",
    "Latacunga",
    "Tulcán",
    "Babahoyo",
    "Tena",
    "Puyo",
    "Macas",
    "Nueva Loja",
    "Salinas",
    "Bahía de Caráquez",
    "Otavalo",
    "Guaranda",
  ],
  Estonia: [
    "Tallinn",
    "Tartu",
    "Narva",
    "Pärnu",
    "Kohtla-Järve",
    "Viljandi",
    "Rakvere",
    "Sillamäe",
    "Maardu",
    "Kuressaare",
    "Võru",
    "Valga",
    "Haapsalu",
    "Jõhvi",
    "Paide",
    "Keila",
    "Saue",
    "Elva",
    "Tapa",
    "Põlva",
  ],
  Finland: [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Lahti",
    "Kuopio",
    "Pori",
    "Joensuu",
    "Lappeenranta",
    "Hämeenlinna",
    "Vaasa",
    "Seinäjoki",
    "Rovaniemi",
    "Mikkeli",
    "Kotka",
    "Salo",
    "Porvoo",
    "Kouvola",
    "Hyvinkää",
    "Järvenpää",
    "Rauma",
    "Tuusula",
  ],
  Georgia: [
    "Tbilisi",
    "Kutaisi",
    "Batumi",
    "Rustavi",
    "Zugdidi",
    "Gori",
    "Poti",
    "Kobuleti",
    "Khashuri",
    "Samtredia",
    "Senaki",
    "Zestaponi",
    "Marneuli",
    "Telavi",
    "Akhaltsikhe",
    "Ozurgeti",
    "Kaspi",
    "Chiatura",
    "Tskaltubo",
    "Kareli",
  ],
  Greece: [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Rhodes",
    "Ioannina",
    "Chania",
    "Chalcis",
    "Kalamata",
    "Kavala",
    "Serres",
    "Alexandroupoli",
    "Xanthi",
    "Katerini",
    "Trikala",
    "Lamia",
    "Komotini",
    "Veria",
    "Corfu",
    "Mytilene",
    "Agrinio",
    "Kozani",
    "Drama",
  ],
  "Hong Kong": [
    "Central",
    "Tsim Sha Tsui",
    "Causeway Bay",
    "Wan Chai",
    "Mong Kok",
    "Admiralty",
    "Sheung Wan",
    "Quarry Bay",
    "Tai Po",
    "Sha Tin",
    "Tuen Mun",
    "Yuen Long",
    "Tsuen Wan",
    "Kwun Tong",
    "Wong Tai Sin",
    "Sham Shui Po",
    "Kowloon City",
    "Yau Tsim Mong",
    "Islands",
    "North",
  ],
  Croatia: [
    "Zagreb",
    "Split",
    "Rijeka",
    "Osijek",
    "Zadar",
    "Slavonski Brod",
    "Pula",
    "Karlovac",
    "Sisak",
    "Šibenik",
    "Varaždin",
    "Velika Gorica",
    "Dubrovnik",
    "Bjelovar",
    "Vinkovci",
    "Vukovar",
    "Koprivnica",
    "Požega",
    "Čakovec",
    "Trogir",
    "Makarska",
    "Rovinj",
    "Poreč",
    "Opatija",
    "Hvar",
  ],
  Hungary: [
    "Budapest",
    "Debrecen",
    "Szeged",
    "Miskolc",
    "Pécs",
    "Győr",
    "Nyíregyháza",
    "Kecskemét",
    "Székesfehérvár",
    "Szombathely",
    "Érd",
    "Tatabánya",
    "Kaposvár",
    "Békéscsaba",
    "Zalaegerszeg",
    "Sopron",
    "Eger",
    "Nagykanizsa",
    "Dunaújváros",
    "Hódmezővásárhely",
    "Salgótarján",
    "Cegléd",
    "Veszprém",
    "Baja",
    "Szolnok",
  ],
  Indonesia: [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Bekasi",
    "Medan",
    "Tangerang",
    "Depok",
    "Semarang",
    "Palembang",
    "Makassar",
    "South Tangerang",
    "Batam",
    "Bogor",
    "Pekanbaru",
    "Bandar Lampung",
    "Padang",
    "Malang",
    "Denpasar",
    "Samarinda",
    "Tasikmalaya",
    "Pontianak",
    "Balikpapan",
    "Banjarmasin",
    "Jambi",
    "Cimahi",
    "Surakarta",
    "Manado",
    "Yogyakarta",
    "Cilegon",
    "Kupang",
  ],
  Ireland: [
    "Dublin",
    "Cork",
    "Limerick",
    "Galway",
    "Waterford",
    "Drogheda",
    "Dundalk",
    "Bray",
    "Navan",
    "Ennis",
    "Kilkenny",
    "Carlow",
    "Naas",
    "Athlone",
    "Portlaoise",
    "Mullingar",
    "Wexford",
    "Letterkenny",
    "Celbridge",
    "Sligo",
    "Clonmel",
    "Malahide",
    "Newbridge",
    "Tralee",
    "Arklow",
  ],
  Israel: [
    "Jerusalem",
    "Tel Aviv",
    "Haifa",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Netanya",
    "Beer Sheva",
    "Bnei Brak",
    "Holon",
    "Ramat Gan",
    "Ashkelon",
    "Rehovot",
    "Bat Yam",
    "Beit Shemesh",
    "Kfar Saba",
    "Herzliya",
    "Hadera",
    "Modi'in",
    "Nazareth",
    "Lod",
    "Acre",
    "Ramla",
    "Ra'anana",
    "Givatayim",
  ],
  Iraq: [
    "Baghdad",
    "Basra",
    "Mosul",
    "Erbil",
    "Najaf",
    "Karbala",
    "Kirkuk",
    "Sulaymaniyah",
    "Nasiriyah",
    "Amarah",
    "Diwaniyah",
    "Kut",
    "Ramadi",
    "Fallujah",
    "Samarra",
    "Baqubah",
    "Tikrit",
    "Hillah",
    "Dohuk",
    "Zakho",
    "Halabja",
    "Sinjar",
    "Tal Afar",
    "Haditha",
    "Hit",
  ],
  Iran: [
    "Tehran",
    "Mashhad",
    "Isfahan",
    "Karaj",
    "Shiraz",
    "Tabriz",
    "Qom",
    "Ahvaz",
    "Kermanshah",
    "Urmia",
    "Rasht",
    "Zahedan",
    "Hamadan",
    "Kerman",
    "Yazd",
    "Ardabil",
    "Bandar Abbas",
    "Arak",
    "Eslamshahr",
    "Zanjan",
    "Sanandaj",
    "Qazvin",
    "Khorramabad",
    "Gorgan",
    "Dezful",
    "Sabzevar",
    "Abadan",
    "Khorramshahr",
    "Ilam",
    "Bushehr",
  ],
  Iceland: [
    "Reykjavik",
    "Kópavogur",
    "Hafnarfjörður",
    "Akureyri",
    "Reykjanesbær",
    "Garðabær",
    "Mosfellsbær",
    "Árborg",
    "Akranes",
    "Fjarðabyggð",
    "Mulathing",
    "Selfoss",
    "Seltjarnarnes",
    "Vestmannaeyjar",
    "Grindavík",
    "Ísafjörður",
    "Álftanes",
    "Egilsstaðir",
    "Húsavík",
    "Sandgerði",
  ],
  Jordan: [
    "Amman",
    "Zarqa",
    "Irbid",
    "Russeifa",
    "Wadi as-Sir",
    "Aqaba",
    "Madaba",
    "Salt",
    "Mafraq",
    "Jerash",
    "Karak",
    "Tafilah",
    "Ma'an",
    "Ajloun",
    "Sahab",
    "Fuheis",
    "Ain al-Basha",
    "Ramtha",
    "Kufranja",
    "Qadisiyah",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Goyang",
    "Yongin",
    "Seongnam",
    "Bucheon",
    "Cheongju",
    "Ansan",
    "Jeonju",
    "Anyang",
    "Cheonan",
    "Pohang",
    "Uijeongbu",
    "Siheung",
    "Paju",
    "Gimhae",
    "Pyeongtaek",
    "Jinju",
  ],
  Kuwait: [
    "Kuwait City",
    "Al Ahmadi",
    "Hawalli",
    "As Salimiyah",
    "Sabah as Salim",
    "Al Farwaniyah",
    "Al Fahaheel",
    "Ar Riqqah",
    "Khaitan",
    "Abu Halifa",
    "Al Mahboula",
    "Mangaf",
    "Al Fintas",
    "Jleeb Al-Shuyoukh",
    "Abraq Khaitan",
    "Al Jahra",
    "Sulaibiya",
    "Al Wafra",
    "Kabd",
    "Mina Abdullah",
  ],
  Lebanon: [
    "Beirut",
    "Tripoli",
    "Sidon",
    "Tyre",
    "Nabatieh",
    "Zahle",
    "Baalbek",
    "Jounieh",
    "Byblos",
    "Aley",
    "Batroun",
    "Bcharre",
    "Douma",
    "Halba",
    "Hermel",
    "Jezzine",
    "Marjeyoun",
    "Rashaya",
    "Zgharta",
    "Anjar",
  ],
  "Sri Lanka": [
    "Colombo",
    "Dehiwala-Mount Lavinia",
    "Moratuwa",
    "Negombo",
    "Kandy",
    "Kalmunai",
    "Vavuniya",
    "Galle",
    "Trincomalee",
    "Batticaloa",
    "Jaffna",
    "Katunayake",
    "Dambulla",
    "Kolonnawa",
    "Gampaha",
    "Puttalam",
    "Badulla",
    "Kalutara",
    "Bentota",
    "Hikkaduwa",
    "Mirissa",
    "Ella",
    "Nuwara Eliya",
    "Sigiriya",
    "Anuradhapura",
  ],
  Lithuania: [
    "Vilnius",
    "Kaunas",
    "Klaipėda",
    "Šiauliai",
    "Panevėžys",
    "Alytus",
    "Marijampolė",
    "Mažeikiai",
    "Jonava",
    "Utena",
    "Kėdainiai",
    "Telšiai",
    "Visaginas",
    "Tauragė",
    "Ukmergė",
    "Plungė",
    "Kretinga",
    "Šilutė",
    "Radviliškis",
    "Palanga",
  ],
  Luxembourg: [
    "Luxembourg City",
    "Esch-sur-Alzette",
    "Differdange",
    "Dudelange",
    "Ettelbruck",
    "Diekirch",
    "Strassen",
    "Bertrange",
    "Bettembourg",
    "Schifflange",
    "Echternach",
    "Rumelange",
    "Grevenmacher",
    "Capellen",
    "Remich",
    "Mondorf-les-Bains",
    "Redange",
    "Wiltz",
    "Troisvierges",
    "Vianden",
  ],
  Latvia: [
    "Riga",
    "Daugavpils",
    "Liepāja",
    "Jelgava",
    "Jūrmala",
    "Ventspils",
    "Rēzekne",
    "Valmiera",
    "Jēkabpils",
    "Ogre",
    "Tukums",
    "Salaspils",
    "Cēsis",
    "Kuldīga",
    "Saldus",
    "Talsi",
    "Dobele",
    "Krāslava",
    "Bauska",
    "Sigulda",
  ],
  Morocco: [
    "Casablanca",
    "Rabat",
    "Fez",
    "Marrakech",
    "Agadir",
    "Tangier",
    "Meknes",
    "Oujda",
    "Kenitra",
    "Tetouan",
    "Safi",
    "Mohammedia",
    "Khouribga",
    "El Jadida",
    "Beni Mellal",
    "Nador",
    "Taza",
    "Settat",
    "Larache",
    "Ksar el Kebir",
    "Khemisset",
    "Guelmim",
    "Berrechid",
    "Wazzane",
    "Ouarzazate",
  ],
  Monaco: ["Monaco-Ville", "Monte Carlo", "La Condamine", "Fontvieille"],
  Moldova: [
    "Chișinău",
    "Tiraspol",
    "Bălți",
    "Bender",
    "Rîbnița",
    "Cahul",
    "Ungheni",
    "Soroca",
    "Orhei",
    "Dubăsari",
    "Comrat",
    "Ceadîr-Lunga",
    "Strășeni",
    "Căușeni",
    "Drochia",
    "Călărași",
    "Florești",
    "Rezina",
    "Hîncești",
    "Edineț",
  ],
  Montenegro: [
    "Podgorica",
    "Nikšić",
    "Pljevlja",
    "Bijelo Polje",
    "Cetinje",
    "Bar",
    "Herceg Novi",
    "Berane",
    "Budva",
    "Ulcinj",
    "Tivat",
    "Rožaje",
    "Kotor",
    "Danilovgrad",
    "Mojkovac",
    "Plav",
    "Kolašin",
    "Žabljak",
    "Andrijevica",
    "Šavnik",
  ],
  "North Macedonia": [
    "Skopje",
    "Bitola",
    "Kumanovo",
    "Prilep",
    "Tetovo",
    "Veles",
    "Štip",
    "Ohrid",
    "Gostivar",
    "Strumica",
    "Kavadarci",
    "Kočani",
    "Kičevo",
    "Struga",
    "Radoviš",
    "Gevgelija",
    "Debar",
    "Kriva Palanka",
    "Sveti Nikole",
    "Negotino",
  ],
  Malta: [
    "Valletta",
    "Birkirkara",
    "Mosta",
    "Qormi",
    "Żabbar",
    "San Pawl il-Baħar",
    "Sliema",
    "Naxxar",
    "Żejtun",
    "Ħamrun",
    "Fgura",
    "Żurrieq",
    "Rabat",
    "Marsaskala",
    "Attard",
    "Paola",
    "Tarxien",
    "Pietà",
    "Marsa",
    "Dingli",
  ],
  Mexico: [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Zapopan",
    "Nezahualcóyotl",
    "Chihuahua",
    "Naucalpan",
    "Mérida",
    "Álvaro Obregón",
    "San Luis Potosí",
    "Aguascalientes",
    "Hermosillo",
    "Saltillo",
    "Mexicali",
    "Culiacán",
    "Guadalupe",
    "Acapulco",
    "Tlalnepantla",
    "Cancún",
    "Querétaro",
    "Chimalhuacán",
    "Torreón",
    "Morelia",
    "Reynosa",
    "Tlaquepaque",
    "Playa del Carmen",
  ],
  Malaysia: [
    "Kuala Lumpur",
    "George Town",
    "Ipoh",
    "Shah Alam",
    "Petaling Jaya",
    "Johor Bahru",
    "Seremban",
    "Kuching",
    "Kota Kinabalu",
    "Klang",
    "Malacca City",
    "Alor Setar",
    "Tawau",
    "Iskandar Puteri",
    "Ampang Jaya",
    "Miri",
    "Sandakan",
    "Kuantan",
    "Kota Bharu",
    "Aeon Bukit Tinggi",
    "Sungai Petani",
    "Taiping",
    "Sibu",
    "Kulim",
    "Bintulu",
  ],
  Netherlands: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
    "Breda",
    "Nijmegen",
    "Enschede",
    "Haarlem",
    "Arnhem",
    "Zaanstad",
    "Amersfoort",
    "Apeldoorn",
    "Hoofddorp",
    "'s-Hertogenbosch",
    "Maastricht",
    "Leiden",
    "Dordrecht",
    "Zoetermeer",
    "Zwolle",
    "Deventer",
    "Delft",
  ],
  Norway: [
    "Oslo",
    "Bergen",
    "Stavanger",
    "Trondheim",
    "Fredrikstad",
    "Kristiansand",
    "Sandnes",
    "Tromsø",
    "Sarpsborg",
    "Skien",
    "Ålesund",
    "Sandefjord",
    "Haugesund",
    "Tønsberg",
    "Moss",
    "Drammen",
    "Lillehammer",
    "Bodø",
    "Arendal",
    "Hamar",
    "Ytrebygda",
    "Larvik",
    "Halden",
    "Askøy",
    "Molde",
  ],
  Nepal: [
    "Kathmandu",
    "Pokhara",
    "Lalitpur",
    "Bharatpur",
    "Biratnagar",
    "Birgunj",
    "Dharan",
    "Butwal",
    "Hetauda",
    "Nepalgunj",
    "Dhangadhi",
    "Itahari",
    "Janakpur",
    "Bhairahawa",
    "Mahendranagar",
    "Baglung",
    "Gulariya",
    "Tulsipur",
    "Rajbiraj",
    "Tansen",
  ],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier-Hastings",
    "Dunedin",
    "Palmerston North",
    "Nelson",
    "Rotorua",
    "New Plymouth",
    "Whangarei",
    "Invercargill",
    "Whanganui",
    "Gisborne",
    "Timaru",
    "Pukekohe",
    "Papakura",
    "Hibiscus Coast",
    "Blenheim",
    "Masterton",
    "Levin",
    "Ashburton",
    "Rangiora",
    "Oamaru",
  ],
  Oman: [
    "Muscat",
    "Seeb",
    "Salalah",
    "Bawshar",
    "Sohar",
    "As Suwayq",
    "Ibri",
    "Saham",
    "Barka",
    "Rustaq",
    "Nizwa",
    "Sur",
    "Bahla",
    "Khasab",
    "Shinas",
    "Izki",
    "Jabrin",
    "Duqm",
    "Khor Fakkan",
    "Liwa",
  ],
  Panama: [
    "Panama City",
    "San Miguelito",
    "Tocumen",
    "David",
    "Arraiján",
    "Colón",
    "La Chorrera",
    "Pacora",
    "Penonome",
    "Santiago",
    "Las Tablas",
    "Puerto Armuelles",
    "Aguadulce",
    "Chitré",
    "Changuinola",
    "La Concepción",
    "Ocú",
    "Bugaba",
    "Los Santos",
    "Capira",
  ],
  Peru: [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Huancayo",
    "Piura",
    "Iquitos",
    "Cusco",
    "Chimbote",
    "Huánuco",
    "Tacna",
    "Juliaca",
    "Ica",
    "Sullana",
    "Ayacucho",
    "Chincha Alta",
    "Huaraz",
    "Puno",
    "Tarapoto",
    "Pucallpa",
    "Castilla",
    "Jaén",
    "Tumbes",
    "Huacho",
    "Huaral",
  ],
  Philippines: [
    "Manila",
    "Quezon City",
    "Caloocan",
    "Davao",
    "Cebu City",
    "Zamboanga",
    "Antipolo",
    "Pasig",
    "Taguig",
    "Valenzuela",
    "Dasmariñas",
    "Calamba",
    "Makati",
    "Marikina",
    "Muntinlupa",
    "Las Piñas",
    "Bacoor",
    "General Santos",
    "Parañaque",
    "Malabon",
    "Mandaluyong",
    "Bacolod",
    "San Jose del Monte",
    "Imus",
    "Iloilo City",
  ],
  Pakistan: [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Hyderabad",
    "Gujranwala",
    "Peshawar",
    "Quetta",
    "Islamabad",
    "Sargodha",
    "Sialkot",
    "Bahawalpur",
    "Sukkur",
    "Jhang",
    "Sheikhupura",
    "Larkana",
    "Gujrat",
    "Mardan",
    "Kasur",
    "Rahim Yar Khan",
    "Sahiwal",
    "Okara",
    "Wah Cantonment",
    "Dera Ghazi Khan",
    "Mirpur Khas",
    "Nawabshah",
    "Mingora",
    "Chiniot",
    "Kamoke",
  ],
  Poland: [
    "Warsaw",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
    "Białystok",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Kielce",
    "Gliwice",
    "Zabrze",
    "Bytom",
    "Olsztyn",
    "Bielsko-Biała",
    "Rzeszów",
    "Ruda Śląska",
    "Rybnik",
  ],
  Portugal: [
    "Lisbon",
    "Porto",
    "Vila Nova de Gaia",
    "Amadora",
    "Braga",
    "Funchal",
    "Coimbra",
    "Setúbal",
    "Almada",
    "Agualva-Cacém",
    "Queluz",
    "Rio Tinto",
    "Barreiro",
    "Évora",
    "Vila Franca de Xira",
    "Aveiro",
    "Póvoa de Varzim",
    "Odivelas",
    "Loures",
    "Faro",
    "Felgueiras",
    "Leiria",
    "Viseu",
    "Guimarães",
    "Matosinhos",
  ],
  Qatar: [
    "Doha",
    "Al Rayyan",
    "Umm Salal",
    "Al Wakrah",
    "Al Khor",
    "Dukhan",
    "Lusail",
    "Al Shamal",
    "Mesaieed",
    "Al Thakhira",
    "Al Wukair",
    "Al Ghuwariyah",
    "Ras Laffan",
    "Al Jumayliyah",
    "Fuwayrit",
    "Al Kharrara",
    "Simaisma",
    "Al Arish",
    "Umm Bab",
    "Al Zubarah",
  ],
  Romania: [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
    "Galați",
    "Ploiești",
    "Oradea",
    "Brăila",
    "Arad",
    "Pitești",
    "Sibiu",
    "Bacău",
    "Târgu Mureș",
    "Baia Mare",
    "Buzău",
    "Botoșani",
    "Satu Mare",
    "Râmnicu Vâlcea",
    "Drobeta-Turnu Severin",
    "Suceava",
    "Piatra Neamț",
    "Târgu Jiu",
  ],
  Serbia: [
    "Belgrade",
    "Novi Sad",
    "Niš",
    "Kragujevac",
    "Subotica",
    "Zrenjanin",
    "Pančevo",
    "Čačak",
    "Novi Pazar",
    "Kraljevo",
    "Smederevo",
    "Leskovac",
    "Užice",
    "Vranje",
    "Valjevo",
    "Kruševac",
    "Šabac",
    "Sombor",
    "Kikinda",
    "Loznica",
    "Jagodina",
    "Zaječar",
    "Pirot",
    "Vršac",
    "Bor",
  ],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
    "Kazan",
    "Chelyabinsk",
    "Omsk",
    "Samara",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Perm",
    "Voronezh",
    "Volgograd",
    "Krasnodar",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Ulyanovsk",
    "Irkutsk",
    "Vladivostok",
    "Yaroslavl",
    "Habarovsk",
    "Makhachkala",
    "Tomsk",
    "Orenburg",
    "Kemerovo",
  ],
  Sweden: [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
    "Lund",
    "Umeå",
    "Gävle",
    "Borås",
    "Södertälje",
    "Eskilstuna",
    "Halmstad",
    "Växjö",
    "Karlstad",
    "Sundsvall",
    "Trollhättan",
    "Östersund",
    "Borlänge",
    "Falun",
    "Skövde",
  ],
  Singapore: [
    "Singapore City",
    "Jurong West",
    "Woodlands",
    "Tampines",
    "Sengkang",
    "Hougang",
    "Yishun",
    "Bedok",
    "Ang Mo Kio",
    "Toa Payoh",
    "Choa Chu Kang",
    "Pasir Ris",
    "Punggol",
    "Clementi",
    "Bukit Batok",
    "Bukit Merah",
    "Geylang",
    "Kallang",
    "Queenstown",
    "Serangoon",
  ],
  Slovenia: [
    "Ljubljana",
    "Maribor",
    "Celje",
    "Kranj",
    "Velenje",
    "Koper",
    "Novo Mesto",
    "Ptuj",
    "Trbovlje",
    "Kamnik",
    "Jesenice",
    "Nova Gorica",
    "Domžale",
    "Škofja Loka",
    "Murska Sobota",
    "Slovenj Gradec",
    "Krško",
    "Postojna",
    "Litija",
    "Ajdovščina",
  ],
  Slovakia: [
    "Bratislava",
    "Košice",
    "Prešov",
    "Žilina",
    "Banská Bystrica",
    "Nitra",
    "Trnava",
    "Martin",
    "Trenčín",
    "Poprad",
    "Prievidza",
    "Zvolen",
    "Považská Bystrica",
    "Michalovce",
    "Spišská Nová Ves",
    "Komárno",
    "Levice",
    "Humenné",
    "Bardejov",
    "Liptovský Mikuláš",
  ],
  Thailand: [
    "Bangkok",
    "Nonthaburi",
    "Pak Kret",
    "Hat Yai",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Udon Thani",
    "Surat Thani",
    "Khon Kaen",
    "Nakhon Ratchasima",
    "Chiang Rai",
    "Lampang",
    "Krabi",
    "Rayong",
    "Hua Hin",
    "Kanchanaburi",
    "Ayutthaya",
    "Sukhothai",
    "Phitsanulok",
    "Nakhon Si Thammarat",
    "Songkhla",
    "Samui",
    "Trang",
    "Phetchaburi",
  ],
  Tunisia: [
    "Tunis",
    "Sfax",
    "Sousse",
    "Ettadhamen",
    "Kairouan",
    "Gabès",
    "Bizerte",
    "Ariana",
    "Gafsa",
    "Monastir",
    "Ben Arous",
    "Kasserine",
    "Médenine",
    "Nabeul",
    "Tataouine",
    "Béja",
    "Jendouba",
    "Mahdia",
    "Siliana",
    "Kef",
    "Tozeur",
    "Kebili",
    "Zaghouan",
    "Manouba",
    "Sidi Bouzid",
  ],
  Taiwan: [
    "Taipei",
    "Kaohsiung",
    "Taichung",
    "Tainan",
    "Taoyuan",
    "Hsinchu",
    "Keelung",
    "Chiayi",
    "Changhua",
    "Pingtung",
    "Yunlin",
    "Nantou",
    "Miaoli",
    "Yilan",
    "Hualien",
    "Taitung",
    "Penghu",
    "Kinmen",
    "Lienchiang",
    "New Taipei",
  ],
  Ukraine: [
    "Kyiv",
    "Kharkiv",
    "Odesa",
    "Dnipro",
    "Donetsk",
    "Zaporizhzhia",
    "Lviv",
    "Kryvyi Rih",
    "Mykolaiv",
    "Mariupol",
    "Luhansk",
    "Vinnytsia",
    "Makiivka",
    "Sevastopol",
    "Simferopol",
    "Kherson",
    "Poltava",
    "Chernihiv",
    "Cherkasy",
    "Zhytomyr",
    "Sumy",
    "Horlivka",
    "Rivne",
    "Kamianske",
    "Ternopil",
  ],
  Uruguay: [
    "Montevideo",
    "Salto",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Maldonado",
    "Tacuarembó",
    "Melo",
    "Mercedes",
    "Artigas",
    "Minas",
    "San José de Mayo",
    "Durazno",
    "Florida",
    "Barros Blancos",
    "Ciudad de la Costa",
    "Treinta y Tres",
    "Rocha",
    "San Carlos",
    "Pando",
  ],
  Uzbekistan: [
    "Tashkent",
    "Namangan",
    "Samarkand",
    "Andijan",
    "Nukus",
    "Bukhara",
    "Qarshi",
    "Kokand",
    "Margilan",
    "Fergana",
    "Jizzakh",
    "Urgench",
    "Gulistan",
    "Navoiy",
    "Angren",
    "Chirchiq",
    "Termez",
    "Bekabad",
    "Khiva",
    "Kattakurgan",
  ],
  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
    "San Cristóbal",
    "Maturín",
    "Ciudad Bolívar",
    "Cumana",
    "Mérida",
    "Barcelona",
    "Turmero",
    "Cabimas",
    "Santa Teresa del Tuy",
    "Barinas",
    "Trujillo",
    "Puerto La Cruz",
    "Los Teques",
    "Acarigua",
    "Araure",
    "El Tigre",
    "Coro",
    "Guanare",
    "San Fernando de Apure",
  ],
  Vietnam: [
    "Ho Chi Minh City",
    "Hanoi",
    "Hai Phong",
    "Da Nang",
    "Bien Hoa",
    "Hue",
    "Nha Trang",
    "Can Tho",
    "Rach Gia",
    "Qui Nhon",
    "Vung Tau",
    "Nam Dinh",
    "Phan Thiet",
    "Long Xuyen",
    "Ha Long",
    "Thai Nguyen",
    "Thanh Hoa",
    "Buon Ma Thuot",
    "My Tho",
    "Vinh",
    "Da Lat",
    "Cao Lanh",
    "Pleiku",
    "Kon Tum",
    "Hoi An",
  ],
  "South Africa": [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Pietermaritzburg",
    "Benoni",
    "Tembisa",
    "Germiston",
    "Soweto",
    "Randburg",
    "Centurion",
    "Midrand",
    "Roodepoort",
    "Boksburg",
    "Klerksdorp",
    "Welkom",
    "Newcastle",
    "Carletonville",
    "Middelburg",
    "Vereeniging",
    "Uitenhage",
    "Polokwane",
  ],
  Kenya: [
    "Nairobi",
    "Mombasa",
    "Nakuru",
    "Eldoret",
    "Kisumu",
    "Thika",
    "Malindi",
    "Kitale",
    "Garissa",
    "Kakamega",
    "Machakos",
    "Meru",
    "Nyeri",
    "Kericho",
    "Embu",
    "Migori",
    "Homa Bay",
    "Naivasha",
    "Kilifi",
    "Isiolo",
    "Nanyuki",
    "Bungoma",
    "Webuye",
    "Mumias",
    "Lamu",
  ],
}

// Havaalanı kodları (sadece uçuş formu için)
export const airportCodes = {
  // Turkey
  Istanbul: "IST/SAW",
  Ankara: "ESB",
  Izmir: "ADB",
  Antalya: "AYT",
  Adana: "ADA",
  Trabzon: "TZX",
  Gaziantep: "GZT",
  Kayseri: "ASR",
  Erzurum: "ERZ",
  Van: "VAN",
  Diyarbakır: "DIY",
  Samsun: "SZF",
  Denizli: "DNZ",
  Malatya: "MLX",
  Elazığ: "EZS",
  Batman: "BAL",
  Muğla: "DLM/BJV",
  Hatay: "HTY",

  // UAE
  Dubai: "DXB/DWC",
  "Abu Dhabi": "AUH",
  Sharjah: "SHJ",
  "Ras Al Khaimah": "RKT",
  "Al Ain": "AAN",
  Fujairah: "FJR",

  // Saudi Arabia
  Riyadh: "RUH",
  Jeddah: "JED",
  Dammam: "DMM",
  Medina: "MED",
  Taif: "TIF",
  Abha: "AHB",
  Tabuk: "TUU",
  Hail: "HAS",
  Najran: "EAM",
  Jazan: "GIZ",
  Yanbu: "YNB",
  "Al Bahah": "ABT",
  Arar: "RAE",
  "Al Qassim": "ELQ",
  "Al Khobar": "DMM",
  Jubail: "DMM",
  AlUla: "ULH",
  Neom: "NEOM",
  "Al Ahsa": "HOF",
  Dhahran: "DHA",
  Mecca: "JED",

  // Egypt
  Cairo: "CAI",
  Alexandria: "HBE",
  "Sharm El Sheikh": "SSH",
  Hurghada: "HRG",
  Luxor: "LXR",
  Aswan: "ASW",
  "Marsa Alam": "RMF",
  Taba: "TCP",
  "Abu Simbel": "ABS",

  // United States
  "New York": "JFK/LGA/EWR",
  "Los Angeles": "LAX",
  Chicago: "ORD/MDW",
  Houston: "IAH/HOU",
  Phoenix: "PHX",
  Philadelphia: "PHL",
  "San Antonio": "SAT",
  "San Diego": "SAN",
  Dallas: "DFW/DAL",
  "San Jose": "SJC",
  Austin: "AUS",
  Jacksonville: "JAX",
  "Fort Worth": "DFW",
  Columbus: "CMH",
  "San Francisco": "SFO",
  Charlotte: "CLT",
  Indianapolis: "IND",
  Seattle: "SEA",
  Denver: "DEN",
  "Washington DC": "DCA/IAD/BWI",
  Boston: "BOS",
  "Las Vegas": "LAS",
  Detroit: "DTW",
  Minneapolis: "MSP",
  Miami: "MIA",
  Atlanta: "ATL",
  Orlando: "MCO",
  Tampa: "TPA",

  // United Kingdom
  London: "LHR/LGW/STN/LTN",
  Manchester: "MAN",
  Birmingham: "BHX",
  Glasgow: "GLA",
  Edinburgh: "EDI",
  Liverpool: "LPL",
  Bristol: "BRS",
  Newcastle: "NCL",
  Leeds: "LBA",
  Belfast: "BFS/BHD",
  Cardiff: "CWL",
  Aberdeen: "ABZ",
  Southampton: "SOU",
  Norwich: "NWI",
  Exeter: "EXT",

  // France
  Paris: "CDG/ORY",
  Nice: "NCE",
  Lyon: "LYS",
  Marseille: "MRS",
  Toulouse: "TLS",
  Bordeaux: "BOD",
  Nantes: "NTE",
  Strasbourg: "SXB",
  Montpellier: "MPL",
  Lille: "LIL",
  Brest: "BES",
  "Clermont-Ferrand": "CFE",
  Perpignan: "PGF",
  Tours: "TUF",
  Caen: "CFR",

  // Germany
  Berlin: "BER",
  Munich: "MUC",
  Frankfurt: "FRA",
  Hamburg: "HAM",
  Düsseldorf: "DUS",
  Cologne: "CGN",
  Stuttgart: "STR",
  Hanover: "HAJ",
  Nuremberg: "NUE",
  Dresden: "DRS",
  Leipzig: "LEJ",
  Bremen: "BRE",
  Dortmund: "DTM",
  Münster: "FMO",
  Karlsruhe: "FKB",

  // Italy
  Rome: "FCO/CIA",
  Milan: "MXP/LIN/BGY",
  Naples: "NAP",
  Venice: "VCE",
  Florence: "FLR",
  Bologna: "BLQ",
  Turin: "TRN",
  Palermo: "PMO",
  Catania: "CTA",
  Bari: "BRI",
  Genoa: "GOA",
  Verona: "VRN",
  Trieste: "TRS",
  Cagliari: "CAG",
  Pisa: "PSA",

  // Spain
  Madrid: "MAD",
  Barcelona: "BCN",
  Valencia: "VLC",
  Seville: "SVQ",
  Málaga: "AGP",
  Palma: "PMI",
  "Las Palmas": "LPA",
  Bilbao: "BIO",
  Alicante: "ALC",
  Zaragoza: "ZAZ",
  "A Coruña": "LCG",
  Vigo: "VGO",
  Granada: "GRX",
  Jerez: "XRY",
  Santander: "SDR",

  // Japan
  Tokyo: "NRT/HND",
  Osaka: "KIX/ITM",
  Nagoya: "NGO",
  Sapporo: "CTS/OKD",
  Fukuoka: "FUK",
  Okinawa: "OKA",
  Sendai: "SDJ",
  Hiroshima: "HIJ",
  Kagoshima: "KOJ",
  Kumamoto: "KMJ",
  Niigata: "KIJ",
  Matsuyama: "MYJ",
  Kochi: "KCZ",
  Miyazaki: "KMI",

  // China
  Beijing: "PEK/PKX",
  Shanghai: "PVG/SHA",
  Guangzhou: "CAN",
  Shenzhen: "SZX",
  Chengdu: "CTU",
  Kunming: "KMG",
  "Xi'an": "XIY",
  Hangzhou: "HGH",
  Nanjing: "NKG",
  Qingdao: "TAO",
  Dalian: "DLC",
  Shenyang: "SHE",
  Harbin: "HRB",
  Wuhan: "WUH",
  Changsha: "CSX",

  // India
  Mumbai: "BOM",
  Delhi: "DEL",
  Bangalore: "BLR",
  Chennai: "MAA",
  Kolkata: "CCU",
  Hyderabad: "HYD",
  Ahmedabad: "AMD",
  Pune: "PNQ",
  Kochi: "COK",
  Goa: "GOI",
  Jaipur: "JAI",
  Lucknow: "LKO",
  Thiruvananthapuram: "TRV",
  Coimbatore: "CJB",
  Indore: "IDR",

  // Brazil
  "São Paulo": "GRU/CGH",
  "Rio de Janeiro": "GIG/SDU",
  Brasília: "BSB",
  Salvador: "SSA",
  Fortaleza: "FOR",
  "Belo Horizonte": "CNF/PLU",
  Manaus: "MAO",
  Curitiba: "CWB",
  Recife: "REC",
  "Porto Alegre": "POA",
  Belém: "BEL",
  Goiânia: "GYN",
  Campinas: "VCP",
  Florianópolis: "FLN",
  Vitória: "VIX",

  // Australia
  Sydney: "SYD",
  Melbourne: "MEL",
  Brisbane: "BNE",
  Perth: "PER",
  Adelaide: "ADL",
  "Gold Coast": "OOL",
  Cairns: "CNS",
  Darwin: "DRW",
  Hobart: "HBA",
  Canberra: "CBR",
  Newcastle: "NTL",
  Townsville: "TSV",
  Ballina: "BNK",
  Launceston: "LST",
  "Alice Springs": "ASP",

  // Canada
  Toronto: "YYZ/YTZ",
  Vancouver: "YVR",
  Montreal: "YUL",
  Calgary: "YYC",
  Edmonton: "YEG",
  Ottawa: "YOW",
  Winnipeg: "YWG",
  "Quebec City": "YQB",
  Halifax: "YHZ",
  Victoria: "YYJ",
  Saskatoon: "YXE",
  Regina: "YQR",
  "St. John's": "YYT",
  "Thunder Bay": "YQT",
  Kelowna: "YKA",

  // Other major cities with airports
  Amsterdam: "AMS",
  Brussels: "BRU",
  Zurich: "ZUR",
  Geneva: "GVA",
  Vienna: "VIE",
  Copenhagen: "CPH",
  Stockholm: "ARN",
  Oslo: "OSL",
  Helsinki: "HEL",
  Warsaw: "WAW",
  Prague: "PRG",
  Budapest: "BUD",
  Athens: "ATH",
  Lisbon: "LIS",
  Porto: "OPO",
  Dublin: "DUB",
  Reykjavik: "KEF",
  Luxembourg: "LUX",
  Malta: "MLA",
  Cyprus: "LCA",
  "Tel Aviv": "TLV",
  Doha: "DOH",
  "Kuwait City": "KWI",
  Muscat: "MCT",
  Bahrain: "BAH",
  Amman: "AMM",
  Beirut: "BEY",
  Baghdad: "BGW",
  Tehran: "IKA",
  Almaty: "ALA",
  Tashkent: "TAS",
  Baku: "GYD",
  Tbilisi: "TBS",
  Yerevan: "EVN",
  Kabul: "KBL",
  Islamabad: "ISB",
  Karachi: "KHI",
  Lahore: "LHE",
  Dhaka: "DAC",
  Colombo: "CMB",
  Kathmandu: "KTM",
  Male: "MLE",
  Jakarta: "CGK",
  Singapore: "SIN",
  "Kuala Lumpur": "KUL",
  Bangkok: "BKK/DMK",
  Manila: "MNL",
  "Ho Chi Minh City": "SGN",
  Hanoi: "HAN",
  "Phnom Penh": "PNH",
  Vientiane: "VTE",
  Yangon: "RGN",
  Seoul: "ICN/GMP",
  Busan: "PUS",
  Taipei: "TPE/TSA",
  "Hong Kong": "HKG",
  Macau: "MFM",
  Ulaanbaatar: "ULN",
  Nairobi: "NBO",
  Cairo: "CAI",
  Casablanca: "CMN",
  Johannesburg: "JNB",
  "Cape Town": "CPT",
  Lagos: "LOS",
  "Addis Ababa": "ADD",
  Khartoum: "KRT",
  Tunis: "TUN",
  Algiers: "ALG",
  Tripoli: "TIP",
  "Buenos Aires": "EZE/AEP",
  Santiago: "SCL",
  Lima: "LIM",
  Bogotá: "BOG",
  Caracas: "CCS",
  Quito: "UIO",
  "La Paz": "LPB",
  Asunción: "ASU",
  Montevideo: "MVD",
  "Panama City": "PTY",
  "San José": "SJO",
  "Guatemala City": "GUA",
  "Mexico City": "MEX",
  Havana: "HAV",
  Kingston: "KIN",
  "Port of Spain": "POS",
}

// Diğer ülkeler için varsayılan şehirler
export const defaultCities = ["Capital City", "Major City 1", "Major City 2", "Major City 3", "Major City 4"]

// Araba tipleri - çoklu dil desteği ile
export const getCarTypes = (t) => [
  { value: "economy", label: t.economy },
  { value: "compact", label: t.compact },
  { value: "midsize", label: t.midsize },
  { value: "fullsize", label: t.fullsize },
  { value: "suv", label: t.suv },
  { value: "luxury", label: t.luxury },
  { value: "convertible", label: t.convertible },
  { value: "van", label: t.van },
  { value: "premium", label: t.premium },
]

// Otel yıldız sayıları - çoklu dil desteği ile
export const getHotelStars = (t) => [
  { value: "1", label: t.oneStar },
  { value: "2", label: t.twoStars },
  { value: "3", label: t.threeStars },
  { value: "4", label: t.fourStars },
  { value: "5", label: t.fiveStars },
]

// Uçuş sınıfları - çoklu dil desteği ile
export const getFlightClasses = (t) => [
  { value: "economy", label: t.economy },
  { value: "premiumEconomy", label: t.premiumEconomy },
  { value: "business", label: t.business },
  { value: "first", label: t.first },
]

// Vites tipleri - çoklu dil desteği ile
export const getTransmissionTypes = (t) => [
  { value: "automatic", label: t.automatic },
  { value: "manual", label: t.manual },
  { value: "semiAutomatic", label: t.semiAutomatic },
]

// Yakıt tipleri - çoklu dil desteği ile
export const getFuelTypes = (t) => [
  { value: "petrol", label: t.petrol },
  { value: "diesel", label: t.diesel },
  { value: "hybrid", label: t.hybrid },
  { value: "electric", label: t.electric },
  { value: "lpg", label: t.lpg },
]

// Havaalanı kodu ile şehir adını birleştiren fonksiyon
export const getCityWithAirport = (cityName) => {
  const airportCode = airportCodes[cityName]
  return airportCode ? `${cityName} (${airportCode})` : cityName
}
